import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";
const here=path.dirname(fileURLToPath(import.meta.url)), out=here, work=path.join(here,"work/defence-dependencies"), date="2026-09-25";fs.mkdirSync(work,{recursive:true});
const weights={H:0.35,E:0.20,D:0.20,X:0.15,R:0.05,A:0.05};
const evidence=[
 {id:"EV-001",country:"Ukraine",event:"Repeated attacks on electricity infrastructure",system:"energy",documented_consequences:"Electricity loss propagated to water, sewage, sanitation, heating, hot water, health, education, economy and displacement; vulnerable groups disproportionately affected",metrics_available:"attack period; affected services; qualitative recovery burden",vector_use:"X and R evidence; H/E context",confidence:"A",source:"UN OHCHR",url:"https://ukraine.ohchr.org/en/Attacks-on-Ukraines-Energy-Infrastructure-Harm-to-the-Civilian-Population"},
 {id:"EV-002",country:"Gaza / multiple conflicts",event:"Degradation of urban essential services",system:"water-energy-health",documented_consequences:"Cumulative deterioration of electricity, water and sanitation creates public-health risk, displacement and long rebuilding times",metrics_available:"cross-conflict operational evidence; service-chain examples",vector_use:"X, R and E evidence",confidence:"A",source:"ICRC",url:"https://www.icrc.org/en/document/urban-services-protracted-conflict-report"},
 {id:"EV-003",country:"Gaza",event:"Fuel, electricity and WASH disruption affecting health care",system:"health-water-energy-logistics",documented_consequences:"Reduced ambulance response, non-functional medical equipment, rationed dialysis, unsafe water and increased infectious-disease risk",metrics_available:"documented service effects; no universal conversion to scores",vector_use:"X and E consequence pathways",confidence:"A",source:"WHO",url:"https://www.emro.who.int/images/stories/palestine/WHO_WHO_oPt_Operational_Plan_April_2024.pdf?ua=1"},
 {id:"EV-004",country:"United States",event:"2003 Northeast blackout dependency example",system:"energy-transport-communications",documented_consequences:"Power loss affected around 50 million people; rail services stopped and cell sites failed after backup batteries drained",metrics_available:"population scale; dependency sequence",vector_use:"X dependency timing",confidence:"A",source:"NIST SP 1190 v2",url:"https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.1190v2.pdf"},
 {id:"EV-005",country:"United States",event:"Defence-installation utility disruptions",system:"defence-utilities",documented_consequences:"Electricity and potable-water disruptions can threaten mission support; outage duration and mitigation require consistent reporting",metrics_available:"utility type; outage duration; mission impact; mitigation",vector_use:"D input schema and R",confidence:"A",source:"US GAO-15-749",url:"https://www.gao.gov/products/gao-15-749"},
 {id:"EV-006",country:"United States",event:"Defence-owned utility condition and outages",system:"defence-energy",documented_consequences:"Utility failures can hamper operations; comparable condition and outage records are needed for investment and resilience decisions",metrics_available:"outage cause, duration, impact; facility-condition information",vector_use:"D, R and evidence quality",confidence:"A",source:"US GAO-17-27",url:"https://www.gao.gov/products/gao-17-27"},
 {id:"EV-007",country:"NATO members",event:"Civil preparedness and military support",system:"government-energy-water-health-comms-transport",documented_consequences:"Continuity of government, essential services and civil support to military depend on resilient energy, water, mass-casualty, communications and transport systems",metrics_available:"seven baseline requirement categories",vector_use:"dependency taxonomy and D boundary",confidence:"A",source:"NATO",url:"https://www.nato.int/en/what-we-do/deterrence-and-defence/resilience-civil-preparedness-and-article-3"},
 {id:"EV-008",country:"Multiple",event:"Essential-service repair access during armed conflict",system:"energy-water-workforce-logistics",documented_consequences:"Service continuity depends on protected operators, repair crews, safe access, spare parts, transport and coordination",metrics_available:"repair access, workforce, logistics and service continuity indicators",vector_use:"R and X inputs",confidence:"A",source:"ICRC / Norwegian Red Cross",url:"https://www.icrc.org/en/publication/keeping-lights-and-taps-running-protecting-and-facilitating-safer-access-essential"},
];
const archetypes=[
 {id:"AR-01",function:"Continuity of government and crisis coordination",civil_dependencies:"electricity; secure communications; transport; staff access; data services",consequences:"Delayed decisions, degraded public warning and emergency coordination",public_D:"unavailable",operator_fields:"capability share; minimum function; substitute site; activation time; replacement fraction"},
 {id:"AR-02",function:"Civil-military communications support",civil_dependencies:"commercial telecoms; electricity; data centres; spectrum; repair workforce",consequences:"Loss of coordination plus spillover to emergency services and public communications",public_D:"unavailable",operator_fields:"approved service band; backup endurance; alternate links; restoration stages"},
 {id:"AR-03",function:"Air mobility and aviation support",civil_dependencies:"airport operations; fuel; navigation; weather; communications; ground transport",consequences:"Interrupted passenger/cargo movement, medical/logistics delays and possible authorised capability loss",public_D:"unavailable",operator_fields:"abstract capability share; substitute availability; duration severity; recovery milestones"},
 {id:"AR-04",function:"Maritime mobility and port support",civil_dependencies:"port access; fuel; pilots/tugs; communications; customs; roads/rail",consequences:"Cargo, fuel and supply-chain disruption with civilian and authorised consequences",public_D:"unavailable",operator_fields:"approved throughput band; alternatives; backlog; restoration milestones"},
 {id:"AR-05",function:"Medical and mass-casualty support",civil_dependencies:"power; water; oxygen; fuel; transport; communications; medical supply chain",consequences:"Reduced treatment capacity, delayed evacuation and increased mortality risk",public_D:"unavailable",operator_fields:"protected capacity band; surge capacity; transfer capacity; backup endurance"},
 {id:"AR-06",function:"Logistics, maintenance and repair support",civil_dependencies:"transport; fuel; warehouses; workforce; suppliers; communications",consequences:"Slower repair, reduced availability and prolonged recovery across dependent services",public_D:"unavailable",operator_fields:"stock endurance; lead times; repair teams; substitute suppliers; access constraints"},
 {id:"AR-07",function:"Shared energy and utility support",civil_dependencies:"grid power; gas/fuel; water; wastewater; backup generation; refuelling",consequences:"Concurrent degradation of mission support and civilian essential services",public_D:"unavailable",operator_fields:"backup endurance; load priority; islanding; refuel interval; restoration stages"},
 {id:"AR-08",function:"Personnel mobilisation and access",civil_dependencies:"roads; public transport; communications; childcare; healthcare; housing",consequences:"Reduced staffing, delayed response and competition with civilian movement needs",public_D:"unavailable",operator_fields:"minimum staffing band; travel-time threshold; alternate reporting locations"},
];
const scenarios=[
 {id:"S01",name:"External power loss",duration:"2h / 24h / 72h",observe:"backup endurance; refuelling; load shedding; water/telecom effects",dimensions:"E,D,X,R"},
 {id:"S02",name:"Communications degradation",duration:"2h / 24h",observe:"alternate links; public warning; emergency coordination; data availability",dimensions:"D,X,R"},
 {id:"S03",name:"Water or sanitation interruption",duration:"12h / 72h",observe:"potable reserve; hygiene; cooling; healthcare; workforce sustainability",dimensions:"H,E,D,X,R"},
 {id:"S04",name:"Fuel/logistics constraint",duration:"24h / 7d",observe:"generator endurance; vehicle/air/marine operations; repair access; medical supply",dimensions:"E,D,X,R,A"},
 {id:"S05",name:"Transport/access interruption",duration:"6h / 48h",observe:"staff arrival; evacuation; deliveries; alternate routes; civilian congestion",dimensions:"H,E,D,X,R"},
 {id:"S06",name:"Workforce availability loss",duration:"1 shift / 3d",observe:"minimum staffing; specialist roles; fatigue; contractor dependence",dimensions:"D,X,R"},
 {id:"S07",name:"Multi-service cascade",duration:"24h / 7d",observe:"non-overlapping downstream effects; sequence and timing; common-cause failure",dimensions:"H,E,D,X,R,A"},
 {id:"S08",name:"Recovery-access constraint",duration:"days / months",observe:"safe access; spares; specialist labour; testing; temporary service",dimensions:"E,D,X,R"},
];
const dependencyTemplate=[
 {field:"record_id",type:"string",required:"yes",example:"DEP-0001",rule:"Non-sensitive identifier"},
 {field:"source_function",type:"controlled category",required:"yes",example:"shared_energy_support",rule:"Use archetype, not site name"},
 {field:"dependent_function",type:"controlled category",required:"yes",example:"medical_support",rule:"Record direction explicitly"},
 {field:"dependency_type",type:"physical/cyber/geographic/logical/workforce/supply",required:"yes",example:"physical",rule:"NIST dependency dimensions"},
 {field:"minimum_service_fraction",type:"0-1 range",required:"operator",example:"",rule:"Null until approved"},
 {field:"backup_endurance_hours",type:"low/central/high",required:"operator",example:"",rule:"Do not infer from equipment presence"},
 {field:"affected_beneficiaries",type:"low/central/high",required:"operator or public service data",example:"",rule:"Prevent E/X double count"},
 {field:"loss_fraction",type:"0-1 range",required:"scenario",example:"",rule:"Version with scenario"},
 {field:"outage_hours",type:"hours range",required:"scenario",example:"",rule:"Distinguish disruption from restoration"},
 {field:"alternative_capacity_fraction",type:"0-1 range",required:"operator",example:"",rule:"Distance alone is not capacity"},
 {field:"recovery_30h_60h_90h",type:"three hour ranges",required:"operator",example:"",rule:"Functional recovery, not repair completion"},
 {field:"information_state",type:"enum",required:"yes",example:"restricted_input",rule:"measured/derived/operator/restricted/assumption/unavailable"},
 {field:"confidence",type:"A-E",required:"yes",example:"",rule:"Unavailable must be E with null values"},
 {field:"source_version",type:"string",required:"yes",example:"",rule:"No sensitive narrative required"},
];
const authorisedD=[
 {field:"profile_id",allowed:"opaque ID",description:"Non-geographic identifier",public_default:"null"},
 {field:"capability_share",allowed:"0-1 band",description:"Approved share of abstract capability",public_default:"null"},
 {field:"loss_fraction",allowed:"0-1 band",description:"Scenario-specific functional loss",public_default:"null"},
 {field:"duration_severity",allowed:"0-1 band",description:"Approved mapping from disruption duration",public_default:"null"},
 {field:"replacement_fraction",allowed:"0-1 band",description:"Approved substitute capability available",public_default:"null"},
 {field:"minimum_capability_breach",allowed:"true/false/null",description:"Non-compensatory authorised flag",public_default:"null"},
 {field:"D_score",allowed:"0-100",description:"100 × share × loss × duration × (1-replacement)",public_default:"null"},
 {field:"evidence_version",allowed:"string",description:"Owning-system version only",public_default:"null"},
 {field:"confidence",allowed:"A-E",description:"Authorised confidence grade",public_default:"E"},
];
function esc(x){const s=x==null?"":String(x);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}function writeCsv(name,data){const h=Object.keys(data[0]);fs.writeFileSync(path.join(out,name),[h.join(","),...data.map(r=>h.map(k=>esc(r[k])).join(","))].join("\n"));return h}
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(work,{recursive:true});const eh=writeCsv("input_global_evidence.csv",evidence),ah=writeCsv("input_archetypes.csv",archetypes),sh=writeCsv("input_resilience.csv",scenarios),dh=writeCsv("input_template.csv",dependencyTemplate),Dheaders=writeCsv("input_D_contract.csv",authorisedD);
fs.writeFileSync(path.join(out,"input_metadata.json"),JSON.stringify({title:"Abstract defence and sensitive-dependency consequence evidence",retrieved:date,scope:"Global public evidence and non-geographic templates only",vector:["H","E","D","X","R","A"],weights,warning:"Do not use this package to identify, map, rank or infer specific defence sites, readiness, vulnerabilities or single points of failure. D remains null until supplied through an authorised interface."},null,2));
const wb=Workbook.create(),read=wb.worksheets.add("Read Me"),ev=wb.worksheets.add("Global Evidence"),ar=wb.worksheets.add("Archetypes"),sc=wb.worksheets.add("Scenarios"),dep=wb.worksheets.add("Dependency Template"),dc=wb.worksheets.add("Authorised D Contract");
function col(n){let s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}function title(ws,t,sub,last){ws.mergeCells(`A2:${last}2`);ws.getRange("A2").values=[[t]];ws.getRange("A2").format={font:{bold:true,size:16,color:"#183B56"}};ws.mergeCells(`A3:${last}3`);ws.getRange("A3").values=[[sub]];ws.getRange("A3").format={font:{italic:true,color:"#526477"}}}function table(ws,start,h,d,name){ws.getRange(`A${start}:${col(h.length)}${start}`).values=[h];ws.getRange(`A${start+1}:${col(h.length)}${start+d.length}`).values=d.map(x=>h.map(k=>x[k]));const t=ws.tables.add(`A${start}:${col(h.length)}${start+d.length}`,true,name);t.style="TableStyleMedium2";ws.freezePanes.freezeRows(start)}
title(read,"Defence and sensitive-dependency evidence","Global consequences, abstract resilience archetypes and an authorised D interface","J");read.getRange("A6:B13").values=[["Metric","Value"],["Global evidence records",evidence.length],["Dependency archetypes",archetypes.length],["Stress scenarios",scenarios.length],["D public values",0],["Geographic defence records",0],["Vector","H, E, D, X, R, A"],["Retrieved",date]];read.getRange("A6:B6").format={fill:"#183B56",font:{bold:true,color:"#FFFFFF"}};read.getRange("A16:A21").values=[["Boundary"],["This package does not identify, map, rank or infer any Singapore defence site, capability, readiness state, vulnerability or dependency route."],["Global cases are consequence evidence, not attack-effect coefficients."],["D stays null until an authorised owner supplies an abstract approved value."],["Dependencies are recorded by function and service consequence, without location or technical configuration."],["Missing values remain null; they are never converted to zero."]];for(let r=16;r<=21;r++)read.mergeCells(`A${r}:J${r}`);read.getRange("A16:J16").format={fill:"#FFF0C7",font:{bold:true,color:"#725000"}};read.getRange("A:J").format.columnWidth=20;
title(ev,"Global evidence","Primary-source observations of cascading consequences and resilience needs",col(eh.length));table(ev,6,eh,evidence,"Evidence");
title(ar,"Dependency archetypes","Non-geographic functions and the civilian systems on which they commonly rely",col(ah.length));table(ar,6,ah,archetypes,"Archetypes");
title(sc,"Stress scenarios","Generic resilience tests; not threat, strike or targeting scenarios",col(sh.length));table(sc,6,sh,scenarios,"Scenarios");
title(dep,"Dependency input template","Fields for approved dependency evidence while preventing hidden assumptions",col(dh.length));table(dep,6,dh,dependencyTemplate,"Dependencies");
title(dc,"Authorised D contract","Minimal abstract interface; all public defaults are null",col(Dheaders.length));table(dc,6,Dheaders,authorisedD,"DContract");
for(const ws of [ev,ar,sc,dep,dc]){const used=ws.getUsedRange();used.format.rowHeight=44;for(let i=1;i<=used.columnCount;i++)ws.getRange(`${col(i)}:${col(i)}`).format.columnWidth=i===1?24:42}for(const ws of [read,ev,ar,sc,dep,dc])ws.showGridlines=false;
wb.recalculate();const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!",options:{useRegex:true,maxResults:100},summary:"formula error scan"});const previews={"Read Me":"A1:J22","Global Evidence":"A1:I15","Archetypes":"A1:F16","Scenarios":"A1:E16","Dependency Template":"A1:E22","Authorised D Contract":"A1:D18"};for(const [n,r] of Object.entries(previews)){const p=await wb.render({sheetName:n,range:r,scale:1,format:"png"});fs.writeFileSync(path.join(work,`${n.replaceAll(" ","-").toLowerCase()}.png`),new Uint8Array(await p.arrayBuffer()))}const x=await SpreadsheetFile.exportXlsx(wb);await x.save(path.join(out,"input_evidence.xlsx"));console.log(JSON.stringify({evidence:evidence.length,archetypes:archetypes.length,scenarios:scenarios.length,errors:err.ndjson},null,2));
