"""Public interface for the isolated continuous-event simulation layer."""
from .engine import SimulationEngine
from .models import (MAX_CANDIDATES_PER_PAIR, MAX_INTERCEPTORS, MAX_THREATS,
                     EPISODE_SCHEMA_VERSIONS, SIMULATOR_VERSION, AbsoluteCandidate, Assignment,
                     AssignmentStatus, EpisodeSpec, EventKind, EventRecord,
                     InterceptorResource, ResolutionKind, ScheduledThreat,
                     ThreatStatus)
from .provider import (ConsequenceProvider, DeterministicToyProvider,
                       ObjectiveDirection, ProviderEvaluation, provider_identity)
from .assignment_planning import (AssignmentDecision, AssignmentPlan,
                                  candidate_universes, feasible_immediate_plan,
                                  optimal_fixed_rank_plan)
from .baseline import (BaselineRun, OnlinePolicyRun,
                       FeasibleImmediateMatchingPolicy,
                       ImmediateInterceptionPolicy, NaiveLaunchOnDetectionPolicy,
                       OptimalFixedRankAssignmentPolicy,
                       replay_assignment_plan)
from .recording import (ROLLOUT_SCHEMA_VERSION, JsonlRolloutRecorder,
                        RolloutRecord, observation_reference, replay_rollout)
from .scenarios import (SCENARIO_GENERATOR_VERSION, SeededScenarioGenerator,
                        generate_episode)
from .singapore_scenario import (SINGAPORE_EPISODE_SCHEMA_VERSION,
                                 SINGAPORE_SCENARIO_VERSION,
                                 SINGAPORE_OBJECTIVE_REFERENCE_VERSION,
                                 MainIslandGeometry, SingaporeGenerationError,
                                 SingaporeScenarioConfig,
                                 SingaporeScenarioGenerator,
                                 canonical_episode_hash, episode_to_dict,
                                 load_main_island)
from .scenario_distribution import (
    DEFAULT_DISTRIBUTION_PATH, PROFILE_NAMES,
    SINGAPORE_DISTRIBUTION_VERSION, SINGAPORE_SCENARIO_V2_VERSION,
    SingaporeScenarioDistribution, SingaporeScenarioV2Generator,
    canonical_distribution_checksum, ingress_sector,
    load_scenario_distribution, profile_predicate_failures,
    scenario_graph_metrics, terminal_grid_cell)
from .singapore_provider import (CONSEQUENCE_CATALOG_VERSION,
                                 SINGAPORE_PROVIDER_VERSION,
                                 CandidateAssessment, ConsequenceCatalog,
                                 SingaporeConsequenceProvider,
                                 build_consequence_catalog)
from .suites import (FROZEN_SPLIT_PROFILES, FROZEN_SPLIT_SEEDS,
                     HELD_OUT_TEST_SEEDS, OOD_CADENCE_SEEDS,
                     OOD_GEOGRAPHY_SEEDS, ORACLE_MAX_ACTION_SEQUENCES,
                     ORACLE_SEEDS, SINGAPORE_ASSIGNMENT_REFERENCE_SUITE,
                     SINGAPORE_REFERENCE_SEEDS, SMOKE_TRAINING_STEPS, STRESS_SEEDS,
                     SUITES, SUITE_MANIFEST_VERSION, VALIDATION_SEEDS,
                     SuiteDefinition, build_suite_manifest,
                     frozen_scenario_plan)
from .scenario_manifest import (
    DEFAULT_SCENARIO_MANIFEST_PATH, MANIFEST_PROVIDER_IDENTITY,
    SCENARIO_REF_PATTERN, ScenarioIdentityMismatch, ScenarioManifest,
    build_frozen_scenario_manifest, build_frozen_scenario_manifest_parallel,
    load_scenario_manifest, manifest_public_metadata, resolve_scenario_ref,
    validate_scenario_ref, verify_all_scenario_references)
from .scenario_pool import (
    SCENARIO_POOL_RECORD_FORMAT, SCENARIO_POOL_SCHEMA_VERSION,
    SCENARIO_POOL_SELECTOR_VERSION, TRAINING_POOL_PROFILE_WEIGHTS,
    EpisodePoolFactory, EpisodePoolScenarioGenerator, ScenarioPool,
    episode_from_dict, generate_scenario_pool, load_scenario_pool,
    training_pool_plan, scenario_content_hash, validate_pool_release_id,
    verify_scenario_pool)
from .factories import (GENERATOR_CHOICES, PROVIDER_CHOICES,
                        runtime_factories)
from .audit import (AUDIT_SEED_START, CANONICAL_AUDIT_COUNTS,
                    DIMENSIONS_CONSIDERED, NAIVE_COMPLETION_THRESHOLDS,
                    SCENARIO_AUDIT_VERSION, audit_episode,
                    canonical_audit_plan, evaluate_goldilocks_gates,
                    render_audit_markdown, run_scenario_audit,
                    run_scenario_audit_parallel,
                    summarize_audit, write_canonical_audit)

__all__ = [
    'SIMULATOR_VERSION', 'EPISODE_SCHEMA_VERSIONS', 'MAX_THREATS', 'MAX_INTERCEPTORS',
    'MAX_CANDIDATES_PER_PAIR', 'ScheduledThreat', 'InterceptorResource',
    'EpisodeSpec', 'AbsoluteCandidate', 'Assignment', 'AssignmentStatus',
    'ThreatStatus', 'ResolutionKind', 'EventKind', 'EventRecord',
    'ConsequenceProvider', 'ProviderEvaluation', 'ObjectiveDirection',
    'DeterministicToyProvider', 'provider_identity', 'SimulationEngine',
    'SCENARIO_GENERATOR_VERSION', 'SeededScenarioGenerator', 'generate_episode',
    'SINGAPORE_SCENARIO_VERSION', 'SINGAPORE_EPISODE_SCHEMA_VERSION',
    'SINGAPORE_OBJECTIVE_REFERENCE_VERSION',
    'SingaporeScenarioConfig', 'SingaporeScenarioGenerator',
    'SingaporeGenerationError', 'MainIslandGeometry', 'load_main_island',
    'episode_to_dict', 'canonical_episode_hash',
    'SINGAPORE_SCENARIO_V2_VERSION', 'SINGAPORE_DISTRIBUTION_VERSION',
    'DEFAULT_DISTRIBUTION_PATH', 'PROFILE_NAMES',
    'SingaporeScenarioDistribution', 'SingaporeScenarioV2Generator',
    'canonical_distribution_checksum', 'load_scenario_distribution',
    'ingress_sector', 'terminal_grid_cell', 'scenario_graph_metrics',
    'profile_predicate_failures',
    'SINGAPORE_PROVIDER_VERSION', 'CONSEQUENCE_CATALOG_VERSION',
    'CandidateAssessment', 'ConsequenceCatalog', 'SingaporeConsequenceProvider',
    'build_consequence_catalog',
    'AssignmentDecision', 'AssignmentPlan', 'candidate_universes',
    'feasible_immediate_plan', 'optimal_fixed_rank_plan',
    'BaselineRun', 'OnlinePolicyRun', 'FeasibleImmediateMatchingPolicy',
    'NaiveLaunchOnDetectionPolicy',
    'ImmediateInterceptionPolicy', 'OptimalFixedRankAssignmentPolicy',
    'replay_assignment_plan', 'ROLLOUT_SCHEMA_VERSION',
    'RolloutRecord', 'JsonlRolloutRecorder', 'observation_reference',
    'replay_rollout',
    'SMOKE_TRAINING_STEPS', 'VALIDATION_SEEDS', 'HELD_OUT_TEST_SEEDS',
    'STRESS_SEEDS', 'ORACLE_SEEDS', 'ORACLE_MAX_ACTION_SEQUENCES',
    'SINGAPORE_REFERENCE_SEEDS', 'SINGAPORE_ASSIGNMENT_REFERENCE_SUITE',
    'SuiteDefinition', 'SUITES',
    'SUITE_MANIFEST_VERSION', 'build_suite_manifest',
    'OOD_GEOGRAPHY_SEEDS', 'OOD_CADENCE_SEEDS',
    'FROZEN_SPLIT_PROFILES', 'FROZEN_SPLIT_SEEDS',
    'frozen_scenario_plan', 'DEFAULT_SCENARIO_MANIFEST_PATH',
    'MANIFEST_PROVIDER_IDENTITY', 'SCENARIO_REF_PATTERN',
    'ScenarioIdentityMismatch', 'ScenarioManifest', 'validate_scenario_ref',
    'load_scenario_manifest',
    'build_frozen_scenario_manifest',
    'build_frozen_scenario_manifest_parallel', 'resolve_scenario_ref',
    'verify_all_scenario_references', 'manifest_public_metadata',
    'SCENARIO_POOL_SCHEMA_VERSION', 'SCENARIO_POOL_RECORD_FORMAT',
    'SCENARIO_POOL_SELECTOR_VERSION', 'TRAINING_POOL_PROFILE_WEIGHTS',
    'ScenarioPool', 'EpisodePoolScenarioGenerator', 'EpisodePoolFactory',
    'validate_pool_release_id', 'training_pool_plan', 'episode_from_dict',
    'scenario_content_hash', 'generate_scenario_pool', 'load_scenario_pool',
    'verify_scenario_pool',
    'PROVIDER_CHOICES', 'GENERATOR_CHOICES', 'runtime_factories',
    'SCENARIO_AUDIT_VERSION', 'AUDIT_SEED_START',
    'CANONICAL_AUDIT_COUNTS', 'NAIVE_COMPLETION_THRESHOLDS',
    'DIMENSIONS_CONSIDERED', 'canonical_audit_plan', 'audit_episode',
    'run_scenario_audit', 'run_scenario_audit_parallel',
    'summarize_audit', 'evaluate_goldilocks_gates',
    'render_audit_markdown', 'write_canonical_audit',
]
